AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  # Rails:
  #   Enabled: true
  DisplayCopNames: true
  StyleGuideCopsOnly: true

Metrics/LineLength:
  Max: 100

# Metrics/MethodLength:
#   Max: 15

# Metrics/AbcSize:
#   Max: 20

# Style/CommentAnnotation:
#   Enabled: false

# Style/Documentation:
#   Enabled: false