# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37cfe659f742947bdf0d6a03d846a7cd1adb54c1b74cf9ef311d46c830458e306501acc80cfe39fc255b3199fcdc6e3bba92c03296451290c21ffa01a325dac9

test:
  secret_key_base: 4c40a51e943f8455b5e66d6b33dab8ebd12ca4bdcb063b84275d69e9364f3bf7b548feab24b9364450b7793f7316b289c9fecd57ae404ef9008de50f9b2cd41f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
